version: "2"
services:
  grafana:
    image: "grafana-beta:latest"
    ports:
      - "3000:3000"
    volumes:
      - "./data:/grafana/data"
    links:
      - "influx"
  influx:
    image: "tutum/influxdb:latest"
    ports:
      - "8083:8083"
      - "8086:8086"
